<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.0.0.1</Version>
    <PackageProjectUrl>https://github.com/goatcorp/AetherTouch</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\Data\goat.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Buttplug" Version="5.0.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.5" />
  </ItemGroup>
</Project>
